const LOGIN_CALL_REQUEST = "LOGIN_CALL_REQUEST";
const LOGIN_CALL_SUCCESS = "LOGIN_CALL_SUCCESS";
const LOGIN_CALL_FAILURE = "LOGIN_CALL_FAILURE";

export { LOGIN_CALL_REQUEST, LOGIN_CALL_SUCCESS, LOGIN_CALL_FAILURE };
