const LOGIN_CALL_REQUEST = "LOGIN_CALL_REQUEST";
const LOGIN_CALL_SUCCESS = "LOGIN_CALL_SUCCESS";
const LOGIN_CALL_FAILURE = "LOGIN_CALL_FAILURE";
const SET_CURRENT_USER = "SET_CURRENT_USER";

export {
  LOGIN_CALL_REQUEST,
  LOGIN_CALL_SUCCESS,
  LOGIN_CALL_FAILURE,
  SET_CURRENT_USER
};
