const POST_RIDES_REQUEST = "POST_RIDES_REQUEST";
const POST_RIDES_SUCCESS = "POST_RIDES_SUCCESS";
const POST_RIDES_FAILURE = "POST_RIDES_FAILURE";

export { POST_RIDES_REQUEST, POST_RIDES_SUCCESS, POST_RIDES_FAILURE };
