const REGISTER_CALL_REQUEST = "REGISTER_CALL_REQUEST";
const REGISTER_CALL_SUCCESS = "REGISTER_CALL_SUCCESS";
const REGISTER_CALL_FAILURE = "REGISTER_CALL_FAILURE";

export { REGISTER_CALL_REQUEST, REGISTER_CALL_SUCCESS, REGISTER_CALL_FAILURE };
