const GET_RIDES_REQUEST = "GET_RIDES_REQUEST";
const GET_RIDES_SUCCESS = "GET_RIDES_SUCCESS";
const GET_RIDES_FAILURE = "GET_RIDES_FAILURE";

const GET_RIDE_REQUEST = "GET_RIDE_REQUEST";
const GET_RIDE_SUCCESS = "GET_RIDE_SUCCESS";
const GET_RIDE_FAILURE = "GET_RIDE_FAILURE";

const UPDATE_RIDE_REQUEST = "UPDATE_RIDE_REQUEST";
const UPDATE_RIDE_SUCCESS = "UPDATE_RIDE_SUCCESS";
const UPDATE_RIDE_FAILURE = "UPDATE_RIDE_FAILURE";

const DELETE_RIDE_REQUEST = "DELETE_RIDE_REQUEST";
const DELETE_RIDE_SUCCESS = "DELETE_RIDE_SUCCESS";
const DELETE_RIDE_FAILURE = "DELETE_RIDE_FAILURE";

export {
  GET_RIDES_REQUEST,
  GET_RIDES_SUCCESS,
  GET_RIDES_FAILURE,
  GET_RIDE_REQUEST,
  GET_RIDE_SUCCESS,
  GET_RIDE_FAILURE,
  UPDATE_RIDE_REQUEST,
  UPDATE_RIDE_SUCCESS,
  UPDATE_RIDE_FAILURE,
  DELETE_RIDE_REQUEST,
  DELETE_RIDE_SUCCESS,
  DELETE_RIDE_FAILURE
};
