const GET_RIDES_REQUEST = "GET_RIDES_REQUEST";
const GET_RIDES_SUCCESS = "GET_RIDES_SUCCESS";
const GET_RIDES_FAILURE = "GET_RIDES_FAILURE";

export { GET_RIDES_REQUEST, GET_RIDES_SUCCESS, GET_RIDES_FAILURE };
